# function to set the variable ROS_PATH
# and to create the alias srcros  
function(setup_ros_alias ros_path)
if("$ENV{ROS_PATH}" STREQUAL ${ros_path})
    message("ros variables already exist, not appending ~/.bashrc")
else()
    set(bash_rc "$ENV{HOME}/.bashrc")
    set(envmt "/etc/environment")
    if("$ENV{ROS_PATH}" STREQUAL "")
        message("ros variables haven't been set before, adding alias and path")
        set(ENV{ROS_PATH} "${ros_path}")
        file(APPEND ${bash_rc} "\n\n# path to pac man ros setup file, and alias to source it\n")
        file(APPEND ${bash_rc} "export ROS_PATH='$ENV{ROS_PATH}'\n")
        file(APPEND ${bash_rc} "alias srcros='source $ROS_PATH'\n")
    else()
        message("ros variable is different from current directory. Changing variable, but not adding alias")
        file(APPEND ${bash_rc} "\n\n # pac man bot has moved, changing ros_path\n")
        set(ENV{ROS_PATH} "${ros_path}")
        file(APPEND ${bash_rc} "export ROS_PATH='$ENV{ROS_PATH}'\n")
    endif()
endif()
endfunction()